# Theme Information
name = "twda_v5"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "Modern Hugo theme with TailwindCSS v4.1.11 + DaisyUI v5.0.43 + Alpine.js v3.14.9"
homepage = "https://github.com/username/twda_v5"
tags = ["modern", "responsive", "blog", "portfolio", "tailwindcss", "daisyui", "alpinejs"]
features = ["responsive", "dark-mode", "search", "multilingual", "math", "diagrams", "pwa"]
min_version = "0.147.9"

[author]
  name = "Aaron"
  homepage = "https://github.com/username"

[original]
  name = "twda_v5"
  homepage = "https://github.com/username/twda_v5"
  repo = "https://github.com/username/twda_v5"
