# Hugo v0.147.9 內建資源處理配置
# 整合 ESBuild (JavaScript) + PostCSS (CSS) + 圖片處理

[build]
  # 建構統計 (用於 Tailwind CSS JIT 模式)
  writeStats = true
  
  # 允許在 assets 中使用 JS 配置
  noJSConfigInAssets = false
  
  # 資源緩存策略
  useResourceCacheWhen = "fallback"

# JavaScript 資源緩存破壞者 (ESBuild)
[[build.cachebusters]]
  source = 'assets/.*\\.(js|ts|jsx|tsx)'
  target = 'js'

[[build.cachebusters]]
  source = 'themes/.*/assets/.*\\.(js|ts|jsx|tsx)'
  target = 'js'

# CSS 相關配置緩存破壞者 (PostCSS)
[[build.cachebusters]]
  source = '(postcss|tailwind)\\.config\\.(js|cjs|mjs)'
  target = 'css'

[[build.cachebusters]]
  source = 'assets/.*\\.(css|scss|sass)'
  target = 'css'

[[build.cachebusters]]
  source = 'themes/.*/assets/.*\\.(css|scss|sass)'
  target = 'css'

# 套件相關緩存破壞者
[[build.cachebusters]]
  source = 'package\\.json'
  target = 'js'

[[build.cachebusters]]
  source = 'yarn\\.lock'
  target = 'js'

# 圖片資源緩存破壞者
[[build.cachebusters]]
  source = 'assets/.*\\.(png|jpg|jpeg|gif|svg|webp|avif)'
  target = 'images'

# 數據檔案緩存破壞者
[[build.cachebusters]]
  source = 'data/.*\\.(json|toml|yaml|yml)'
  target = 'data'

# 內容檔案緩存破壞者
[[build.cachebusters]]
  source = 'content/.*\\.md'
  target = 'content'
