# 主導航菜單
[[main]]
  name = "首頁"
  url = "/"
  weight = 10

[[main]]
  name = "文章"
  url = "/blogs/"
  weight = 20

[[main]]
  name = "分類"
  url = "/categories/"
  weight = 30

[[main]]
  name = "標籤"
  url = "/tags/"
  weight = 40

[[main]]
  name = "系列"
  url = "/series/"
  weight = 50

[[main]]
  name = "作者"
  url = "/authors/"
  weight = 60

[[main]]
  name = "關於"
  url = "/about/"
  weight = 70

# 頁尾菜單
[[footer]]
  name = "隱私政策"
  url = "/privacy/"
  weight = 10

[[footer]]
  name = "使用條款"
  url = "/terms/"
  weight = 20

[[footer]]
  name = "聯絡我們"
  url = "/contact/"
  weight = 30

[[footer]]
  name = "網站地圖"
  url = "/sitemap.xml"
  weight = 40

# 側邊欄菜單 (快速連結)
[[sidebar]]
  name = "最新文章"
  url = "/blogs/"
  weight = 10

[[sidebar]]
  name = "熱門標籤"
  url = "/tags/"
  weight = 20

[[sidebar]]
  name = "文章系列"
  url = "/series/"
  weight = 30
