# 自訂輸出格式
[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "index"
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true
  isHTML = false
  noUgly = true
  permalinkable = false

[outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "search"
  isPlainText = true
  isHTML = false
  noUgly = true
  permalinkable = false

# WebApp Manifest 格式 (PWA)
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
baseName = "manifest"
isPlainText = true
notAlternative = true

# Sitemap 格式
[outputFormats.SitemapIndex]
mediaType = "application/xml"
baseName = "sitemap"
isPlainText = true
notAlternative = true

# AMP 頁面格式
[outputFormats.AMP]
mediaType = "text/html"
baseName = "amp/index"
isHTML = true
permalinkable = true
rel = "amphtml"
